### ISSUE TITLE
Question:  How to get terminal into microsoft/iis container

### ISSUE THREAD

**Issue by eyem4usf** [Microsoft/iis-docker#10]
've used the microsoft/iis image in a docker file that creates a site and copies files into the site's directory. Whenever I run the container I get a 404 file not found. I want to look into the container and see if something got messed up with the file copy. I use the command:

docker run -it -p 80:8000 microsoft/iis:2.0

to run the container. If I use the same command and put "cmd" or "powershell" at the end then it just ouputs:
[2J�[H�[37;40m
Service 'w3svc' started

And my session is hung. Is there something about this container that doesn't allow it to accept a command now? Any ideas for how I could manage this container?

**Comment by shirhatti** [comment]
You have a couple of options here:
* You could override the entrypoint by doing `docker run -it --entrypoint powershell microsoft/iis`. This will start your container with `powershell` as the entrypoint application as opposed to `ServiceMonitor.exe`.
* The other option is to start your container in detached mode `docker run -d microsoft/iis` and then connect to your container using `docker exec -it d6c0fe130dba powershell` 

There is some discussion around changing the base image to use the `CMD` directive instead of the `ENTRYPOINT` directive in #9.

Also, it's worth noting that your container isn't hung. It's waiting for a `Ctrl+C` signal.
