### ISSUE TITLE
Cannot start IIS

### ISSUE THREAD

**Issue by KevinBurton** [Microsoft/iis-docker#119]
I have installed docker:
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false

And I have this simple Dockerfile

FROM microsoft/iis
RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
WORKDIR /inetpub/wwwroot
COPY Web/ .

I build the container with 
docker build -t cpp-site .

Then I run it with
docker run -d -p 8000:8000 --name cpp-site cpp-site

I get the address of the running container and then go to my browser (Chrome) and go to the address http://xx.xx.xx.xx:8000 and I just get a timeout error. I looked at the logs (docker logs xxxx returns no output). I tried to exec into the running container to see if I could see anything amiss. Nothing.  Any hints as to how I would find what is tripping up my container?

Thank you.

Kevin

**Comment by wsc9108** [comment]
Hi Kevin, 

I also run into this issue, and have some findings to share, 
1st of all, I think this doc has mistake at this command line
docker run -d -p 8000:8000 --name my-running-site iis-site,
because in the container, there is no opening port 8000 at all, the only open port in it, is 80
#in the container
PS C:\inetpub\wwwroot> netstat -ano | findstr "80"
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       4
  TCP    [::]:80                [::]:0                 LISTENING       4

2nd. To access the container you can do it in two ways, 
*) as you've followed the README, you can access by the IP and port 80, in Chrome, don't use 8000.

or
*) run the command like below, to expose 80 to an unused port on local PC,e.g. 8011,
docker run -d -p 8011:80 --name my-running-site6 iis-jw-site01
then access in Chrome,  127.0.0.1:8011

Hope this help you too.

**Comment by shirhatti** [comment]
@KevinBurton As pointed out by @wcs9108 you're mapping to the incorrect port in the container. Trying mapping to port 80 inside the container instead as that the port the default site binding in IIS is listening on.

**Comment by KevinBurton** [comment]
Thank you. This moved me forward.  Now the Chrome request is giving me "Sorry, an error occurred while processing you request."
