### ISSUE TITLE
Please provide guidance on these images

### ISSUE THREAD

**Issue by kwaazaar** [microsoft/iis-docker#12]
- Nano vs Core: which to use when
- What Dockerfile-content is needed to support WCF (HTTP-activation, etc)
- What volumes to mount to get access to IIS-logfiles, app-logfiles, etc.
- How to run .NET Core sites/api's (Kestrel, etc)

... Or supply links to where this information is available on the web.

**Comment by ztmdsbt** [comment]
Is this repo still in maintenance?

**Comment by bariscaglar** [comment]
The repo is still in maintenance and will be in the foreseeable future, although it will be updated with less frequency from now on since we are starting to use a naming scheme for labels that will be unchanged from month to month.

The purpose of this specific GitHub repo (Microsoft/iis-docker) is for backing the Docker file referenced from the corresponding iis container image ([Microsoft/IIS](https://hub.docker.com/r/microsoft/iis/)) kept in Docker Hub. 

The information on the front page should be a good starting point on how to start. I have assigned this to @shirhatti who can point you to the information that addresses each of your questions.

**Comment by bariscaglar** [comment]
@shirhatti can you take a look at this request? It has been active for too long.
