### ISSUE TITLE
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022

### ISSUE THREAD

**Issue by antt0481** [microsoft/iis-docker#191]
failed to register layer: Error processing tar file(exit status 1): link /Files/Program Files/Common Files/System/ado/en-US/msader15.dll.mui /Files/Program Files (x86)/Common Files/System/ado/en-US/msader15.dll.mui: no such file or directory

I run on my Mac and get that error, could you advice me

**Comment by ntrappe-msft** [comment]
You can't run any Windows Containers natively on a Mac because you have two different operating systems. To use them, you'll need to be running the containers in a VirtualBox or another Windows VM (with Docker). The VM needs to Hi, are you using a Windows VM on your Mac? You can't run any Windows Containers natively on a Mac because you have two different operating systems. To use Windows Containers, you need to have a Windows machine running Docker. If you're working on a Mac, you'll need to use a Windows VM, like VirtualBox, to do so.
