### ISSUE TITLE
HTTPS best practices?

### ISSUE THREAD

**Issue by Cryowatt** [microsoft/iis-docker#30]
What are the best practices for hosting an HTTPS website from within an IIS docker container?

**Comment by rgarita** [comment]
Hello @Cryowatt  i'm trying to do the same thing,,,  any idea,,, were you able to made some progress on this topic?

**Comment by 9Rune5** [comment]
I would love to see some discussion about this.

From my POV it would be a very neat trick if I could simply tell the container what its DNS entry is and it will take care of generating a private key as well as contacting letsencrypt to acquire a publicly trusted certificate.

**Comment by KevinVording** [comment]
I currently login to the IIS Manager remotely and add a certificate this way. It would be nice to have this automated indeed. Very curious about this one.

**Comment by artisticcheese** [comment]
Wondering what is the problem being raised here. What prevents you from just bake SSL cert into the container during build stage?

**Comment by shirhatti** [comment]
# Request for feedback

Let’s first look at the existing approaches, to see their short-comings.

#### Build a container image with the certificates already installed
-	The first variation to this is to build a container image with dev/test/qa/prod certs all installed and all bindings created in a single container image. The obvious downside to this approach is that anyone who can pull the container now has access to your production cert.
-	The second variation to this is to build environment specific images. However, this still doesn’t mitigate the fact that you need access to your production certificate at container build time.
#### Override the entrypoint with a script to install the cert which is volume mounted at run time
-	An alternative approach is to override the entrypoint process with a custom script that install the cert into the cert store from the known location it’s been volume mounted to and then creates the binding. Your script performing the” ceremony” still has to be environment-aware still leading to the possibility to errors surfacing prod but not in dev/test.  Besides the obvious slower startup times, there’s also the burden of ceremony being passed on the user with no tangible benefit.

## Proposal

To improve the experience, we are looking at enabling SSL by default in the IIS base image. After our proposed changes, in addition to the default HTTP binding on port 80, the IIS base image will also contain an HTTPS binding on port 443 that binds to an empty hostname. We will use an existing feature of IIS called  the Central Certificate Store (CCS), which unlike other certificate stores is file-based.
While CCS allows you to configure both directory where the certs live and an account to impersonate while accessing the directory, I suspect these are knobs and switches that most folks won’t need to configure in a container scenario. We can establish a convention for where your certificates should be mapped to (for e.g., C:\inetpub\certs\) and instead of requiring an identity to impersonate we will add a feature that allows us to fall back and use the LocalSystem account.

Note: CCS works by constructing a filename from hostname (from Client Hello) like hostname.pfx and looking for a match in the CCS location. The IIS provider additionally uses the underscore character to indicate a wildcard certificates. If the destination is www.contoso.com, the IIS provider tries to locate www.contoso.com.pfx; if that is unsuccessful, it then it tries to locate _.contoso.com.pfx.
[This blog post](https://blogs.msdn.microsoft.com/kaushal/2012/10/11/central-certificate-store-ccs-with-iis-8-windows-server-2012/) describes how CCS works in greater detail.

The exhaustive list of changes that we are making:
1)	Don’t require an account to impersonate for use with CCS. Allow a fall back to the LocalSystem account.
2)	Changes to IISAdministration PowerShell cmdlets that allow to enable/disable CCS with these new optional parameters.
3)	Add default HTTPS binding on port 443 to an empty hostname (an empty hostname will match any hostname) in IIS container base image.

Example scenarios after this change:

#### I don’t want to use SSL
-	Don’t change your workflow. The HTTP binding will work as expected.
-	If you try and make a HTTPS request over port 443, the server will reply will TCP RST instead of a Server Hello during the SSL handshake as it can’t find a certificate

#### I want to serve my SSL cert regardless of hostname
-	Map your desired cert to C:\inetpub\certs\_.pfx and it will work with no additional configuration changes.

#### I want to bind to multiple hostnames and respond with different certs
-	Map your desired certs to C:\inetpub\certs\foo.com.pfx and C:\inetpub\certs\bar.com.pfx and it will work with no additional configuration changes
-	Note: HTTPS requests to any other hostnames will result in the same TCP RST behavior as described above. It is however possible to use a catch-all cert C:\inetpub\certs\_.pfx  in addition to these certs.

#### I want reject all HTTP requests and only speak HTTPS
-	You will have to make configuration changes to delete the existing HTTP binding

**Comment by artisticcheese** [comment]
I think there shall be another approach as well based on "secrets" when running under orchestrators. Docker swarm allows you to define secrets which live only inside orchestrator hosted containers. That secret can be PFX file and separate secret can be a password. To allow running containers outside of orchestrator information about certificate as well as key is passed via Environment Variable when container is started. This will allow to have certificates in central store and not require volume mappings at run time which is probably biggest problem with proposed approach.

**Comment by shirhatti** [comment]
@artisticcheese There's no limitation preventing you from doing what you proposed. This is only an additive change

**Comment by artisticcheese** [comment]
@shirhatti If CCS is hardmapped in IIS to c:\inetpub\certs then implementing "secrets" will not work since those are hard mapped into `docker\secrets` location which is in completely different location on system. I suggest to have environment variable instead which is passed to container to inform where certs will be stored at instead of hardcoding them in predefined pass as suggested above.

**Comment by shirhatti** [comment]
@artisticcheese Agreed. In fact, I suspect this path will vary based on which orchestrator and we should make it configurable

**Comment by artisticcheese** [comment]
Yes, it'll be different for different orchestrators. In addition to storing PFX file there is another piece which shall be passed through Environment variable which is password for PFX file. I imagine people are not going to put their certs in images even in private registries without password.

**Comment by pcj** [comment]
Workaround: don't even try.   I use caddy for this.  You can dockerize that too.  Have Caddy listen on 80/443 in your VM or docker host, and acts as proxy that will do automatic SSL provisioning for you.  Get your IP from docker inspect, then use/generate a Caddyfile like:

```
my-secure-site.com {
  proxy / 172.28.55.24 {
    transparent
  }
}
```

Then point your browser to <https://my-secure-site.com>.  End of story.

**Comment by cnieren** [comment]
Has there been any more movement on this?

**Comment by JohanSpannare** [comment]
### Here is a way we are currently doing it.

1, Override the Entrypoint with and custom bootstrapper

        entrypoint: powershell C:\\start.ps1

2, Add two environments variables
```
SSL_THUMPRINT: [THUMPRINT TO USE FOR SSL/TLS]
SITENAME: [PATH TO YOUR SITE INSIDE CONTAINER]
```

Bootstrapper start.ps1

```
$securepfxpass = (Get-Content -Path c:\${env:SITENAME}\cert.password.txt) |ConvertTo-SecureString -AsPlainText -Force
Import-PfxCertificate -Password $securepfxpass -CertStoreLocation Cert:\LocalMachine\My -FilePath c:\${env:SITENAME}\cert.pfx   

$binding = New-WebBinding -Name ${env:SITENAME} -Protocol https -IPAddress * -Port 443;
$binding = Get-WebBinding -Name ${env:SITENAME} -Protocol https;
$binding.AddSslCertificate(${env:SSL_THUMPRINT}, "my");

Copy-Item -Path C:\SL.Help\web.config_config -Destination C:\SL.Help\web.config
Start-Process -FilePath C:\ServiceMonitor.exe -ArgumentList w3svc -Wait -PassThru
```

This way we can have the same image in Production and Test. You just inject your secret for cert and cert password into the location you specified in your bootstrapper

**Comment by bariscaglar** [comment]
There's clearly a good amount of information contained here in HTTPS guidance. @shirhatti we just need to centralize it elsewhere and close this issue.

**Comment by eriawan** [comment]
@bariscaglar 

I totally agree! This information contained here should be documented, and it would be best if the actual MS Docs page has this information as "best practice" or "sample use cases" article for IIS on Docker.

**Comment by liberdis** [comment]
@JohanSpannare 
> Bootstrapper start.ps1
> ```
> $securepfxpass = (Get-Content -Path c:\${env:SITENAME}\cert.password.txt) |ConvertTo-SecureString -AsPlainText -Force
> This way we can have the same image in Production and Test. You just inject your secret for cert and cert password into the location you specified in your bootstrapper

What's the difference between reading the clear-text secret from a file inside the container vs passing it in as an environment variable? In both situations you're persisting the secret in plaintext inside the container which is generally seen as the significant problem to solve here. You also don't address the source of these secrets that are held externally to the container - those have to get populated in to the container from somewhere, like a simple COPY or ADD, but now you have to maintain clear-text secrets on persistent media both inside and outside the container. Secrets are a pain in the ass, i guess is what I'm trying to say.

**Comment by JohanSpannare** [comment]
@liberdis By using secrets you dont expose the "secret" to the host. Secrets are like configs, except that they are not readable from outside the container. Only the container it self has access and can read it.
So in my example its safer to use an secret then simply have an environment variable that are both readable from the host, and any administrator of the container platform you are using.

**Comment by liberdis** [comment]
@JohanSpannare 
> Secrets are like configs

I apologize for my apparent ignorance - I'm still learning some of the nuance of windows containers and I am not following you - do you mean you are using an external secrets manager like Vault or implementing an orchestrator with a secrets manager like Docker Swarm?

I thought the context of the discussion was implementing SSL in a singleton (standalone) container, so when you say "like configs" I am unsure what you mean. Can you please expand for me what you mean when you say "secrets are like configs" ? I don't know how cert.password.txt gets in to your container unless you insert it on to the image via dockerfile (COPY/ADD) or by way of a startup script accessing a host volume, and I don't know how either of those happens without the secret becoming exposed on the host as clear text in some form. Thanks in advance for helping me understand !

**Comment by JohanSpannare** [comment]
@liberdis 
I am referring to the Docker Configs and Docker Secrets that are available in Docker Swarm

**Comment by cposton** [comment]
I have most of a container image that handles loading certificates, etc. using a bootstrapper, but the issue I'm running into is not being able to find a way to disable TLS 1.0/1.1 to get past security checks we have. I've performed the registry edits per Microsoft documentation (https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings), but without a way to "reboot", the changes don't take effect. I've tried simply restarting IIS in a variety of ways (i.e. iisreset, PowerShell service restarts), all to no avail. Any ideas on how to get past this stumbling block?

**Comment by artisticcheese** [comment]
Did you try `net stop http & net start http`

**Comment by cposton** [comment]
> Did you try `net stop http & net start http`

I have been unable to stop the http service during the build of the Dockerfile. `net stop http` fails initially due to dependencies, using `net stop /y` gets past that but then it is unable to complete in time for it to time out and return a failure code. I also tried PowerShell `Stop-Service` which I might can get to work with a lot more code to stop dependencies first (using -Force did not work). I will keep trying other mechanisms and report back. Thanks!

**Comment by cposton** [comment]
I'm embarrassed to say that the entire issue was due to a mistakenly typed key path. Apologies.

**Comment by qacollective** [comment]
Microsoft seem to have more official guidance on this kind of thing now.

https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1

**Comment by mclausing** [comment]
> 
> 
> Microsoft seem to have more official guidance on this kind of thing now.
> 
> https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1

That is for Core running on Kestrel. This is for IIS.
