### ISSUE TITLE
Question: Use of environment variables for application pools other than DefaultAppPool?

### ISSUE THREAD

**Issue by mpwaldhorst** [Microsoft/iis-docker#55]
Hi all,
As part of issue #41 a new version of ServiceMonitor was introduced that will forward environment variables passed by the -e argument to the `DefaultAppPool`.

Is there any way to also enable this for other application pools?
Is there any update on what was discussed in #2 with regards to `w3wp.exe`?

**Comment by mcy94w** [comment]
Hi @mpwaldhorst:

Right now servicemonitor.exe only write the Env Var to DefaultAppPool. Is there a reason that you want to use another AppPool instead?

**Comment by mpwaldhorst** [comment]
Hi @mcy94w ,
Yes, I'm currently working on dockerizing some applications which have some more complex requirements.
Consider the following set-up for a website in IIS where we have one IIS hosted website with two applications running in separate AppPools:
* MyIISWebsite (DefaultAppPool)
  * application1 (Application1AppPool)
  * application2 (Application2AppPool)

Normally it would be possible to run all of these in the same application pool, however for process isolation these applications are run in separate application pools.

Splitting these applications among different docker containers does not make sense in this case as these applications are inherently linked and are considered as 1 application from a deployment point of view.

With the current behavior of servicemonitor.exe it is not possible to forward environment variables to the other AppPools.

Would it be possible to let servicemonitor.exe support configuring 1 or more customly named app pools to which the env variables should be set through a command line argument or implement servicemonitor.exe in such a way that it will forward the env variables to all application pools currently in use on the dockerized IIS instance?

**Comment by bariscaglar** [comment]
Unless you have a strong technical reason why you possibly cannot separate the applications into different containers, doing so will be the right pattern for container applications. When we implement features for IIS to be used within containers, we only consider cases where one W3WP application per container is used. This is true for service monitor passing the environment variables or any other feature past, present or future.

Even if you were to find a workaround for the current problem, next one will be around the corner so in my opinion it would be worth the effort to separate applications into separate containers.

**Comment by bariscaglar** [comment]
Please reopen the issue if you have any further questions.

**Comment by tburnett80** [comment]
I couldn't seem to get this to work. I eventually had to override the entry point to run a powershell script for initializing on run.

my script would set the -e variables as machine level vars inside the container, perform web.config transform based on the ASPNET_ENVIRONMENT variable passed ( from this article [https://anthonychu.ca/post/aspnet-web-config-transforms-docker-containers/](ASP.NET Web.config Transforms in Docker Containers) )  And because we can no longer substitute variables from Octopus on deployment inside a web.config that is now in the image I perform a find and replace.
After that I start ServiceMonitor and let it work normally. 

Things are definitely easier once you can move your stuff to Core, but where there is a will, there is a way with Framework.

**Comment by aguyngueran** [comment]
I have just run into this issue when containerizing some legacy app.

I understand that by design separating by the containers looks more clear than using one with different app pools but it doesn't make it easier to put the existing app into the containers.

In my case I was able to have separated the whole into five, six containers. Now I would like to focus myself on other typical monolithic app transition problems and not to tailor even more one of the containers.
