### ISSUE TITLE
Using docker configs for web.config causes 500.19 0x80070005 error

### ISSUE THREAD

**Issue by JohanSpannare** [Microsoft/iis-docker#68]
If you uses docker config for web.config. IIS cant read the file due to not have access to the config.

## Icacls

web.config from docker config

    icacls.exe .\web.config
    .\web.config BUILTIN\Administrators:(F)
                 NT AUTHORITY\SYSTEM:(F)

web.config_ from COPY command

    .\Web.config_ BUILTIN\Administrators:(F)
                  NT AUTHORITY\SYSTEM:(F)
                  BUILTIN\Administrators:(F)
                  BUILTIN\Users:(RX)

### Test from inside container

    Invoke-WebRequest http://localhost

```
Invoke-WebRequest : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>IIS 10.0 Detailed Error - 500.19 - Internal Server Error</title>
...
<div id="content">
<div class="content-container">
  <h3>HTTP Error 500.19 - Internal Server Error</h3>
  <h4>The requested page cannot be accessed because the related configuration data for the page is invalid.</h4>
</div>

<div class="content-container">
 <fieldset><h4>Detailed Error Information:</h4>
  <div id="details-left">
   <table border="0" cellpadding="0" cellspacing="0">
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr>
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;Unknown</td></tr>
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr>
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070005</td></tr>
    <tr class="alt"><th>Config Error</th><td>&nbsp;&nbsp;&nbsp;Cannot read configuration file due to insufficient permissions
</td></tr>
```

### Current workaround

Copy web.config content coming from docker config to web.config and override Entrypoint

    Copy-Item -Path C:\Site\web.config_config -Destination C:\Site\web.config
    Start-Process -FilePath C:\ServiceMonitor.exe -ArgumentList w3svc -Wait -PassThru

### Best practises

What´s the best practices working with IIS and docker configs?

Best reg
Johan Spännare

**Comment by bariscaglar** [comment]
If you have a web.config as part of your web site, it should just be copied as the rest of the content. I don't think you should have to deal with ACLs in any way. What prompted you to play with the ACLs. @mcy94w is this something we do or advocate?

**Comment by JohanSpannare** [comment]
@bariscaglar if you like to have different config for different environments, you cant have your configs inside the image. It will make the image non generic. It also stops you from changing the config if you need.

Error code 500.19 (0x80070005) states that there is an permission error reading config file according to Microsoft support page below.
[https://support.microsoft.com/en-za/help/942055/-http-error-500-19-error-when-you-open-an-iis-7-0-webpage](url)



Best practice is not to have any environment specific configurations inside an image such as web.config. Therefor are we using docker config for handling environment specific configurations.

[https://docs.docker.com/engine/swarm/configs/#example-rotate-a-config](url)

**Comment by jimmyca15** [comment]
@JohanSpannare 

We spent some time looking into the scenario of docker config and IIS. You are correct that docker config is placing incorrect file ACLs on the web.config and that the users group must be able to read that file. What turns out is that many times configuration files must be readable by more than administrators or the local system. This is the case for the web.config in IIS. Thus docker config's assumption on the necessary ACLs may need revisiting.

There is no best practice that we can provide regarding docker config and web.config because of the limitations it has on the ACLs. The workaround you are currently utilizing is the best/only option for solving this limitation. We feel that the ideal solution would be for docker config to provide a way to specify who the config file should be readable by when it inserts the file into the container. This not something we can solve on our own and would need coordination with docker.

We completely agree with the docker config approach and see the value in using it for rotating web.configs. The problem is that its just one piece short from being complete because of the ACL assumption.

**Comment by jimmyca15** [comment]
There is nothing left to track on our end for this issue. If you have any more questions please feel free to reopen the issue or create a new one.
