### ISSUE TITLE
Need guidance to connect to the container using IIS Manager

### ISSUE THREAD

**Issue by cywang16** [Microsoft/iis-docker#77]
Greeting,

I'm able to run this image. Is it possible to connect it with IIS manager from the host? Or via any other kind of tool?

Thanks,

Chun-Yen

**Comment by bariscaglar** [comment]
@cywang16, yes you can connect to it using IIS Manager if you enable wmsvc on the target server, just like on the full server. However, the preferred way going forward will be using manage.iis.net to monitor the container IIS instances. @jimmyca15 is working on the documentation to make this process clear.

**Comment by cywang16** [comment]
Thanks @bariscaglar 

Is it https://manage.iis.net/get?

**Comment by bariscaglar** [comment]
Yes, that's it.

**Comment by cywang16** [comment]
How can I get the access token of IIS in the container? Thanks.

**Comment by jimmyca15** [comment]
Hello @cywang16 

I am in the process of optimizing the IIS Administration API (the download available at [manage.iis.net](https://manage.iis.net)) for containers, as well as writing documentation. As it currently stands the best documentation for getting the API set up in a container can be found in the following issue where the scenario was originally requested for the product https://github.com/Microsoft/IIS.Administration/issues/87

The approach being used to have an access token available in the container is to generate the access token + hash pair using the script located at https://github.com/Microsoft/IIS.Administration/blob/dev/scripts/utils/Generate-ApiKey.ps1 and creating a version of _api-keys.json_ to be used by the API with the hash generated by the script. The details of this are outlined in the issue I linked above.

The access key usage/generation of one of the big pieces that I am currently in the process of optimizing.

**Comment by cywang16** [comment]
Thanks...

I briefly looked [/artisticcheese/IISadmin](https://github.com/artisticcheese/IISadmin). Not fully understand yet, but looks like IIS container will need to install iisadmin.exe for this to work. However, that will require MSI, which is not available on microsoft/iis:nanoserver. Is this known issue, and by design?

**Comment by jimmyca15** [comment]
@cywang16 

The IIS Administration API supports installation through a PowerShell script and this is the intended method for installation on Nano Server. We previously wrote a blog of how to install on Nano Server [here](https://blogs.iis.net/adminapi/microsoft-iis-administration-on-nano-server). The only step that has changed since that blog was written is that the ASP.NET Core module is no longer needed.

I am also in the process of creating a sample dockerfile for running the IIS Administration API on containers. The PR (#82) is being processed currently.

Going forward there will be no new standalone Nano Server and the application model is quite different so it may be a better idea to move to a ServerCore or DataCenter approach rather than Nano Server.

**Comment by artisticcheese** [comment]
Nanoserver have IIS stripped down out of it starting with version 1709. IIS is pretty much dead down the road for future nanoserver versions. I suggest to look for alternatives if you plan to host in nanoserver.
