### ISSUE TITLE
403 - Forbidden: Access is denied.

### ISSUE THREAD

**Issue by shine7430** [Microsoft/iis-docker#92]
403 - Forbidden: Access is denied.

**Comment by mcy94w** [comment]
hi @shine7430 
Could you please elaborate?

**Comment by mcy94w** [comment]
I will close this issue, Feel free to reopen it if you still have problem.

**Comment by erikahub** [comment]
Hi! 
I am trying to access an IIS hosted ASP.NET site from a container. Currently I cannot access the site from my host device. 
I am using:
Docker ver. 2.3.0.4 , Engine 19.03.12
mcr.microsoft.com/windows/servercore/iis:latest as base image

I have access from outside the container to the the Default Web Site and basic sites (HTML and ASP.NET) I have created. I also have access to the websites inside the container using `Invoke-WebRequest -Uri "http://localhost:{Port}" -UseBasicParsing [-UseDefaultCredentials]`. 
One of the sites should be public and not require any credentials, so invoking that one without the default credentials works out. However, I cannot access any of them, public or requiring a login, using the powershell command. The answer is always:
`Forbidden
Fordidden URL
HTTP Error 403. The request URL is forbidden.`

The logs within the container (C:\Windows\System32\LogFiles\HTTPERR) show 403.3, write access forbidden, for the public site, which shouldn't be, since the apppool user and the IIS_IUSRS both have received full access on all files in C:\inetpub\wwwroot, given to them using `icacls C:\inetpub\wwwroot /grant apppool:(OI)(CI)F /t`, same for IIS_IUSRS. Originally I also used "everyone" as the SID for icacls, same result.
